CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y

# Enable 32kHz crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# 轨迹球设置
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
## https://github.com/badjeff/zmk-pmw3610-driver/blob/main/src/pmw3610.c
# 启用PMW3610智能表面适配算法（提升粗糙表面追踪稳定性）
CONFIG_PMW3610_ALT_SMART_ALGORITHM=y

## https://github.com/badjeff/zmk-pmw3610-driver/blob/main/Kconfig
# 交换X/Y轴（比如轨迹球上下滚变成左右滚时启用）
CONFIG_PMW3610_ALT_SWAP_XY=n
# 反转X轴方向（比如向左滚变成向右滚时启用）
CONFIG_PMW3610_ALT_INVERT_X=n
# 反转Y轴方向（比如向上滚变成向下滚时启用）
CONFIG_PMW3610_ALT_INVERT_Y=y

# 轨迹球数据最小上报间隔（单位：毫秒）越大越省电
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=8


# REST1/2/3 的时间可根据需求调整，数值越大，越晚进入更低功耗模式。
CONFIG_PMW3610_ALT_REST1_SAMPLE_TIME_MS=100
CONFIG_PMW3610_ALT_REST2_SAMPLE_TIME_MS=200
CONFIG_PMW3610_ALT_REST3_SAMPLE_TIME_MS=300
# 想更快休眠（省电）：减小RUN_DOWNSHIFT_TIME_MS（比如改成 1000ms）；
# 想更晚休眠（更跟手）：增大RUN_DOWNSHIFT_TIME_MS（比如改成 5000ms）；
CONFIG_PMW3610_ALT_RUN_DOWNSHIFT_TIME_MS=500
CONFIG_PMW3610_ALT_REST1_DOWNSHIFT_TIME_MS=3000
CONFIG_PMW3610_ALT_REST2_DOWNSHIFT_TIME_MS=30000


# CONFIG_PMW3610_ALT_LOG_LEVEL_DBG=y
# CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=300 // <--see Troubleshooting
